# Example configuration file for clickhouse-proto-gen

# ClickHouse connection DSN
dsn: clickhouse://user:password@localhost:9000/mydb

# Tables to generate proto files for (required)
# Can specify as table name or database.table
tables:
  - users
  - orders
  - products

# Output directory for generated proto files
output_dir: ./proto

# Protocol Buffer package name
package: myapp.clickhouse.v1

# Go package import path
go_package: github.com/myorg/myapp/gen/clickhousev1

# Include table and column comments in proto files
include_comments: true

# Maximum page size for List operations (default: 10000)
# Values above this limit will return an error
max_page_size: 10000

# API Generation Options
# These settings control generation of HTTP/REST API annotations using Google API standards

# Enable generation of HTTP annotations for REST API endpoints
# When true, generates google.api.http annotations and field_behavior annotations
enable_api: true

# Base path for API endpoints (used when enable_api is true)
# Example: "/api/v1" results in endpoints like "/api/v1/table_name"
api_base_path: /api/v1

# Table prefixes to expose via REST API (optional)
# Empty list = all tables get API endpoints
# Non-empty list = only tables matching these prefixes get API endpoints
# Example: ["fct_", "dim_"] will only generate APIs for fact and dimension tables
api_table_prefixes: ["fct_"]
