// Package protogen generates protobuf schemas and Go helpers from ClickHouse tables
package protogen

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"

	"github.com/ethpandaops/clickhouse-proto-gen/internal/clickhouse"
)

// rowField describes one generated row struct field and its proto conversion.
type rowField struct {
	goName    string
	goType    string
	column    string
	jsonName  string
	convLines []string
	imports   []string
}

// GenerateRowHelpers generates ClickHouse-scannable row structs for all tables.
// Row field types match the SELECT column expressions produced by the
// BuildList/BuildGet query builders, so rows can be scanned directly with
// clickhouse-go's ScanStruct and converted to proto messages via ToProto.
func (g *Generator) GenerateRowHelpers(tables []*clickhouse.Table) error {
	for _, table := range tables {
		if len(table.Columns) == 0 {
			continue
		}

		if len(table.SortingKey) == 0 {
			continue
		}

		if err := g.generateRowHelper(table); err != nil {
			return err
		}
	}

	return nil
}

// generateRowHelper generates the <table>.row.go file for a single table.
func (g *Generator) generateRowHelper(table *clickhouse.Table) error {
	messageName := getProtocMessageName(table.Name)
	rowName := messageName + "Row"

	fields := make([]*rowField, 0, len(table.Columns))
	imports := map[string]bool{}

	for i := range table.Columns {
		col := &table.Columns[i]

		field := g.buildRowField(col, table.Name)
		for _, imp := range field.imports {
			imports[imp] = true
		}

		fields = append(fields, field)
	}

	sb := &strings.Builder{}
	sb.WriteString("// Code generated by clickhouse-proto-gen. DO NOT EDIT.\n")
	fmt.Fprintf(sb, "// Scannable result row for %s\n\n", table.Name)
	fmt.Fprintf(sb, "package %s\n\n", g.goPackageName())

	writeRowImports(sb, imports)

	fmt.Fprintf(sb, "// %s is a ClickHouse-scannable result row for the %s table.\n", rowName, table.Name)
	fmt.Fprintf(sb, "// Field types match the SELECT column expressions produced by\n")
	fmt.Fprintf(sb, "// BuildList%sQuery and BuildGet%sQuery: DateTime columns are unix\n", messageName, messageName)
	fmt.Fprintf(sb, "// timestamps, DateTime64 columns are unix microseconds, Date and large\n")
	fmt.Fprintf(sb, "// integer and decimal columns are strings, and FixedString columns are\n")
	fmt.Fprintf(sb, "// nullable. Scan rows with clickhouse-go's ScanStruct.\n")
	fmt.Fprintf(sb, "type %s struct {\n", rowName)

	for _, f := range fields {
		fmt.Fprintf(sb, "\t%s %s `ch:\"%s\" json:\"%s\"`\n", f.goName, f.goType, f.column, f.jsonName)
	}

	sb.WriteString("}\n\n")

	fmt.Fprintf(sb, "// TableName returns the ClickHouse table this row maps to.\n")
	fmt.Fprintf(sb, "func (%s) TableName() string {\n\treturn %q\n}\n\n", rowName, table.Name)

	fmt.Fprintf(sb, "// ToProto converts the row to its protobuf message.\n")
	fmt.Fprintf(sb, "func (r *%s) ToProto() *%s {\n", rowName, messageName)
	fmt.Fprintf(sb, "\tp := &%s{}\n\n", messageName)

	for _, f := range fields {
		for _, line := range f.convLines {
			sb.WriteString(line)
			sb.WriteString("\n")
		}
	}

	sb.WriteString("\treturn p\n}\n")

	filename := filepath.Join(g.config.OutputDir, fmt.Sprintf("%s.row.go", table.Name))
	if err := g.writeFile(filename, sb.String()); err != nil {
		return err
	}

	g.log.WithField("file", filename).Info("Generated row helper file")

	return nil
}

// writeRowImports writes the import block for a row helper file.
func writeRowImports(sb *strings.Builder, imports map[string]bool) {
	if len(imports) == 0 {
		return
	}

	keys := make([]string, 0, len(imports))
	for k := range imports {
		keys = append(keys, k)
	}

	sort.Strings(keys)

	stdlib := make([]string, 0, len(keys))
	external := make([]string, 0, len(keys))

	for _, k := range keys {
		if strings.Contains(k, ".") {
			external = append(external, k)
		} else {
			stdlib = append(stdlib, k)
		}
	}

	sb.WriteString("import (\n")

	for _, k := range stdlib {
		fmt.Fprintf(sb, "\t%q\n", k)
	}

	if len(stdlib) > 0 && len(external) > 0 {
		sb.WriteString("\n")
	}

	for _, k := range external {
		if k == wrapperspbImport {
			fmt.Fprintf(sb, "\twrapperspb %q\n", k)
			continue
		}

		fmt.Fprintf(sb, "\t%q\n", k)
	}

	sb.WriteString(")\n\n")
}

const (
	uuidImport       = "github.com/google/uuid"
	wrapperspbImport = "google.golang.org/protobuf/types/known/wrapperspb"

	convDirect     = "direct"
	convInt32Cast  = "int32cast"
	convIPString   = "ipString"
	convUUIDString = "uuidString"

	wrapString = "String"
	wrapInt32  = "Int32"
	wrapInt64  = "Int64"
	wrapUInt32 = "UInt32"
	wrapUInt64 = "UInt64"
	wrapBool   = "Bool"
)

// buildRowField computes the Go type and proto conversion for one column.
func (g *Generator) buildRowField(col *clickhouse.Column, tableName string) *rowField {
	protoFieldName := SanitizeName(col.Name)
	f := &rowField{
		goName:   goCamelCase(protoFieldName),
		column:   col.Name,
		jsonName: protoFieldName,
	}

	// Nullability of the scan target. FixedString results are made nullable by
	// the query builders via NULLIF, and Nullable inside LowCardinality is not
	// reflected in Column.IsNullable.
	rowNullable := !col.IsArray &&
		(strings.Contains(col.Type, "Nullable(") || col.BaseType == typeFixedString)

	// Nullability of the proto field (wrapper types), matching the proto generator.
	pbNullable := col.IsNullable && !col.IsArray

	base := g.rowBaseKind(col, tableName)

	switch {
	case col.BaseType == typeMap:
		f.goType = g.rowMapType(col)
		f.convLines = []string{fmt.Sprintf("\tp.%s = r.%s", f.goName, f.goName)}
	case col.IsArray:
		f.goType = "[]" + base.goType
		f.imports = base.imports
		f.convLines = rowArrayConv(f, base)
	default:
		f.imports = base.imports
		if rowNullable {
			f.goType = "*" + base.goType
			f.convLines = rowNullableConv(f, base, pbNullable)

			if pbNullable {
				f.imports = append(f.imports, wrapperspbImport)
			}
		} else {
			f.goType = base.goType
			f.convLines = rowPlainConv(f, base)
		}
	}

	return f
}

// rowKind describes how a column's scan type converts to its proto type.
type rowKind struct {
	goType  string
	conv    string // one of: direct, int32cast, ipString, uuidString
	wrapper string // wrapperspb constructor name for nullable proto fields
	imports []string
}

// rowBaseKind maps a column's base type to its scan Go type and conversion
// kind. For arrays this describes the element type. The mapping mirrors
// getSelectColumnExpression: types the SELECT rewrites arrive as the rewritten
// type, everything else arrives as-is.
//
//nolint:gocyclo // exhaustive type mapping
func (g *Generator) rowBaseKind(col *clickhouse.Column, tableName string) rowKind {
	// Int64/UInt64 columns configured for string conversion are selected via toString().
	if (col.BaseType == typeUInt64 || col.BaseType == typeInt64) &&
		g.config.Conversion.ShouldConvertToString(tableName, col.Name) {
		return rowKind{goType: protoString, conv: convDirect, wrapper: wrapString}
	}

	switch col.BaseType {
	case typeInt8:
		return rowKind{goType: "int8", conv: convInt32Cast, wrapper: wrapInt32}
	case typeInt16:
		return rowKind{goType: "int16", conv: convInt32Cast, wrapper: wrapInt32}
	case typeInt32:
		return rowKind{goType: protoInt32, conv: convDirect, wrapper: wrapInt32}
	case typeInt64:
		return rowKind{goType: protoInt64, conv: convDirect, wrapper: wrapInt64}
	case clickhouseUInt8, clickhouseUInt16, typeUInt32:
		// UInt8/UInt16 are selected via toUInt32().
		return rowKind{goType: protoUInt32, conv: convDirect, wrapper: wrapUInt32}
	case typeUInt64:
		return rowKind{goType: protoUInt64, conv: convDirect, wrapper: wrapUInt64}
	case typeInt128, typeInt256, typeUInt128, typeUInt256:
		// Selected via toString().
		return rowKind{goType: protoString, conv: convDirect, wrapper: wrapString}
	case typeFloat32:
		return rowKind{goType: "float32", conv: convDirect, wrapper: "Float"}
	case typeFloat64:
		return rowKind{goType: "float64", conv: convDirect, wrapper: "Double"}
	case clickhouseDecimal, clickhouseDecimal32, clickhouseDecimal64, clickhouseDecimal128, clickhouseDecimal256:
		// Selected via toString().
		return rowKind{goType: protoString, conv: convDirect, wrapper: wrapString}
	case typeBool:
		return rowKind{goType: protoBool, conv: convDirect, wrapper: wrapBool}
	case clickhouseDateTime:
		// Selected via toUnixTimestamp().
		return rowKind{goType: protoUInt32, conv: convDirect, wrapper: wrapUInt32}
	case clickhouseDateTime64:
		// Selected via toUnixTimestamp64Micro().
		return rowKind{goType: protoInt64, conv: convDirect, wrapper: wrapInt64}
	case clickhouseDate, clickhouseDate32:
		// Selected via toString().
		return rowKind{goType: protoString, conv: convDirect, wrapper: wrapString}
	case typeUUID:
		return rowKind{goType: "uuid.UUID", conv: convUUIDString, wrapper: wrapString, imports: []string{uuidImport}}
	case typeIPv4, typeIPv6:
		return rowKind{goType: "net.IP", conv: convIPString, wrapper: wrapString, imports: []string{"net"}}
	case "Binary":
		return rowKind{goType: "[]byte", conv: convDirect, wrapper: "Bytes"}
	default:
		// String, FixedString, Enum8/16, JSON, geo types and anything unknown
		// map to string in proto and are selected as-is.
		return rowKind{goType: protoString, conv: convDirect, wrapper: wrapString}
	}
}

// rowMapType returns the Go map type for a Map column, using the same
// key/value mapping as the proto generator's native map fields.
func (g *Generator) rowMapType(col *clickhouse.Column) string {
	tm := NewTypeMapper()
	keyType, valueType := tm.parseMapType(col.Type)

	return fmt.Sprintf("map[%s]%s",
		protoScalarToGo(tm.mapClickHouseTypeToProto(keyType)),
		protoScalarToGo(tm.mapClickHouseTypeToProto(valueType)))
}

// protoScalarToGo converts a proto scalar type name to its Go type.
func protoScalarToGo(protoType string) string {
	switch protoType {
	case protoFloat:
		return "float32"
	case protoDouble:
		return "float64"
	case protoBytes:
		return "[]byte"
	default:
		return protoType
	}
}

// rowPlainConv emits the ToProto assignment for a non-nullable scalar field.
func rowPlainConv(f *rowField, base rowKind) []string {
	switch base.conv {
	case convInt32Cast:
		return []string{fmt.Sprintf("\tp.%s = int32(r.%s)", f.goName, f.goName)}
	case convIPString:
		return []string{
			fmt.Sprintf("\tif len(r.%s) > 0 {", f.goName),
			fmt.Sprintf("\t\tp.%s = r.%s.String()", f.goName, f.goName),
			"\t}",
		}
	case convUUIDString:
		return []string{fmt.Sprintf("\tp.%s = r.%s.String()", f.goName, f.goName)}
	default:
		return []string{fmt.Sprintf("\tp.%s = r.%s", f.goName, f.goName)}
	}
}

// rowNullableConv emits the ToProto assignment for a nullable scan field.
// When the proto field is a wrapper type the value is wrapped, otherwise the
// pointer is dereferenced into the plain proto field.
func rowNullableConv(f *rowField, base rowKind, pbNullable bool) []string {
	lines := []string{fmt.Sprintf("\tif r.%s != nil {", f.goName)}

	value := fmt.Sprintf("*r.%s", f.goName)

	switch base.conv {
	case convInt32Cast:
		value = fmt.Sprintf("int32(*r.%s)", f.goName)
	case convIPString, convUUIDString:
		value = fmt.Sprintf("r.%s.String()", f.goName)
	}

	if pbNullable {
		lines = append(lines, fmt.Sprintf("\t\tp.%s = wrapperspb.%s(%s)", f.goName, base.wrapper, value))
	} else {
		lines = append(lines, fmt.Sprintf("\t\tp.%s = %s", f.goName, value))
	}

	lines = append(lines, "\t}")

	return lines
}

// rowArrayConv emits the ToProto assignment for an array field.
func rowArrayConv(f *rowField, base rowKind) []string {
	switch base.conv {
	case convInt32Cast:
		return []string{
			fmt.Sprintf("\tfor _, v := range r.%s {", f.goName),
			fmt.Sprintf("\t\tp.%s = append(p.%s, int32(v))", f.goName, f.goName),
			"\t}",
		}
	case convIPString, convUUIDString:
		return []string{
			fmt.Sprintf("\tfor _, v := range r.%s {", f.goName),
			fmt.Sprintf("\t\tp.%s = append(p.%s, v.String())", f.goName, f.goName),
			"\t}",
		}
	default:
		return []string{fmt.Sprintf("\tp.%s = r.%s", f.goName, f.goName)}
	}
}

// goPackageName derives the Go package name from the configured go_package.
func (g *Generator) goPackageName() string {
	pkgName := "main"

	if g.config.GoPackage != "" {
		parts := strings.Split(g.config.GoPackage, "/")
		pkgName = parts[len(parts)-1]
		pkgName = strings.ReplaceAll(pkgName, "-", "_")
	}

	return pkgName
}

// goCamelCase converts a proto field name to its Go identifier using the same
// algorithm as protoc-gen-go (protobuf-go internal/strs.GoCamelCase), so row
// struct fields always match the generated .pb.go fields.
//
//nolint:gocyclo // mirrors the upstream algorithm verbatim
func goCamelCase(s string) string {
	var b []byte

	for i := 0; i < len(s); i++ {
		c := s[i]

		switch {
		case c == '.' && i+1 < len(s) && isASCIILower(s[i+1]):
			// Skip over '.' in ".{{lowercase}}".
		case c == '.':
			b = append(b, '_')
		case c == '_' && (i == 0 || s[i-1] == '.'):
			b = append(b, 'X')
		case c == '_' && i+1 < len(s) && isASCIILower(s[i+1]):
			// Skip over '_' in "_{{lowercase}}".
		case isASCIIDigit(c):
			b = append(b, c)
		default:
			if isASCIILower(c) {
				c -= 'a' - 'A'
			}

			b = append(b, c)

			for ; i+1 < len(s) && isASCIILower(s[i+1]); i++ {
				b = append(b, s[i+1])
			}
		}
	}

	return string(b)
}

func isASCIILower(c byte) bool {
	return 'a' <= c && c <= 'z'
}

func isASCIIDigit(c byte) bool {
	return '0' <= c && c <= '9'
}
